export const LIVE_SOL_PRICE = "LIVE_SOL_PRICE";

export const LIVE_TOKEN_PRICES = "LIVE_TOKEN_PRICES";
export const MY_WALLET_INFO = "MY_WALLET_INFO";
export const MY_NEW_TRANSACTION = "MY_NEW_TRANSACTION";

export const PUMP_FUN_TOKENS = "PUMP_FUN_TOKENS";
export const PUMP_SELL_THIS = "PUMP_SELL_THIS";

export const RUG_MAIN_STATUS = "RUG_MAIN_STATUS";
export const RUG_NOTIFY_MESSAGE = "RUG_NOTIFY_MESSAGE";
export const RUG_OWNER_GENERATE = "RUG_OWNER_GENERATE";
export const RUG_MINT_TOKEN = "RUG_MINT_TOKEN";
export const RUG_SELL_ALL = "RUG_SELL_ALL";
